### ISSUE TITLE
cannot build binder dkms module

### ISSUE THREAD

**Issue by luntik2012** [anbox/anbox-modules#24]
```sh
user /tmp/anbox-modules $ sudo dkms install anbox-binder/1

Creating symlink /var/lib/dkms/anbox-binder/1/source ->
                 /usr/src/anbox-binder-1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.1.7-arch1-1-ARCH all KERNEL_SRC=/lib/modules/5.1.7-arch1-1-ARCH/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.1.7-arch1-1-ARCH (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
user /tmp/anbox-modules $ cat /var/lib/dkms/anbox-binder/1/build/make.log 
DKMS make.log for anbox-binder-1 for kernel 5.1.7-arch1-1-ARCH (x86_64)
Thu 06 Jun 2019 10:57:40 AM +03
make -C /lib/modules/5.1.7-arch1-1-ARCH/build V=0 M=$PWD
make[1]: Entering directory '/usr/lib/modules/5.1.7-arch1-1-ARCH/build'
  CC [M]  /var/lib/dkms/anbox-binder/1/build/deps.o
  CC [M]  /var/lib/dkms/anbox-binder/1/build/binder.o
/var/lib/dkms/anbox-binder/1/build/binder.c:3406:11: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
 3406 |  .fault = binder_vm_fault,
      |           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox-binder/1/build/binder.c:3406:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:275: /var/lib/dkms/anbox-binder/1/build/binder.o] Error 1
make[1]: *** [Makefile:1571: _module_/var/lib/dkms/anbox-binder/1/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.1.7-arch1-1-ARCH/build'
make: *** [Makefile:8: all] Error 2

```

**Comment by luntik2012** [comment]
oops, duplicate of #17
