### ISSUE TITLE
bug for install anbox-modules with dkms

### ISSUE THREAD

**Issue by mobin-2008** [anbox/anbox-modules#81]
Hello. Im Using ArchLinux with Gnome 40. My Kernel is 5.12.10-arch1-1.
`
➜  anbox-modules git:(master) sudo dkms --no-depmod -k 5.12.10-arch1-1 install anbox-ashmem/1

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j6 KERNELRELEASE=5.12.10-arch1-1 all KERNEL_SRC=/lib/modules/5.12.10-arch1-1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.10-arch1-1 (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

`
Make File Log:
`
DKMS make.log for anbox-binder-1 for kernel 5.12.10-arch1-1 (x86_64)
‫شنبه ۱۲ ژوئن ۲۱، ساعت ۱۱:۱۸:۴۴ (+0430)‬
make -C /lib/modules/5.12.10-arch1-1/build V=0 M=$PWD
make[1]: Entering directory '/usr/lib/modules/5.12.10-arch1-1/build'
  CC [M]  /var/lib/dkms/anbox-binder/1/build/binder.o
  CC [M]  /var/lib/dkms/anbox-binder/1/build/deps.o
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_get_unused_fd_flags’:
/var/lib/dkms/anbox-binder/1/build/binder.c:444:16: error: implicit declaration of function ‘__alloc_fd’ [-Werror=implicit-function-declaration]
  444 |         return __alloc_fd(files, 0, rlim_cur, flags);
      |                ^~~~~~~~~~
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_fd_install’:
/var/lib/dkms/anbox-binder/1/build/binder.c:454:17: error: implicit declaration of function ‘__fd_install’; did you mean ‘fd_install’? [-Werror=implicit-function-declaration]
  454 |                 __fd_install(proc->files, fd, file);
      |                 ^~~~~~~~~~~~
      |                 fd_install
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_close_fd’:
/var/lib/dkms/anbox-binder/1/build/binder.c:467:18: error: implicit declaration of function ‘__close_fd’; did you mean ‘close_fd’? [-Werror=implicit-function-declaration]
  467 |         retval = __close_fd(proc->files, fd);
      |                  ^~~~~~~~~~
      |                  close_fd
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_update_page_range’:
/var/lib/dkms/anbox-binder/1/build/binder.c:633:33: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  633 |                 down_write(&mm->mmap_sem);
      |                                 ^~~~~~~~
      |                                 mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:683:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  683 |                 up_write(&mm->mmap_sem);
      |                               ^~~~~~~~
      |                               mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:710:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  710 |                 up_write(&mm->mmap_sem);
      |                               ^~~~~~~~
      |                               mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_mmap’:
/var/lib/dkms/anbox-binder/1/build/binder.c:3486:23: error: implicit declaration of function ‘get_files_struct’; did you mean ‘put_files_struct’? [-Werror=implicit-function-declaration]
 3486 |         proc->files = get_files_struct(current);
      |                       ^~~~~~~~~~~~~~~~
      |                       put_files_struct
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /var/lib/dkms/anbox-binder/1/build/binder.o] Error 1
make[1]: *** [Makefile:1851: /var/lib/dkms/anbox-binder/1/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.12.10-arch1-1/build'
`
Help Me.  Thank You

**Comment by mobin-2008** [comment]
Better information below:
Dkms Log:
`➜  anbox-modules git:(master) sudo dkms --no-depmod -k 5.12.10-arch1-1 install anbox-ashmem/1

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j6 KERNELRELEASE=5.12.10-arch1-1 all KERNEL_SRC=/lib/modules/5.12.10-arch1-1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.10-arch1-1 (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.`
Make File Log:
`DKMS make.log for anbox-binder-1 for kernel 5.12.10-arch1-1 (x86_64)
‫شنبه ۱۲ ژوئن ۲۱، ساعت ۱۱:۱۸:۴۴ (+0430)‬
make -C /lib/modules/5.12.10-arch1-1/build V=0 M=$PWD
make[1]: Entering directory '/usr/lib/modules/5.12.10-arch1-1/build'
  CC [M]  /var/lib/dkms/anbox-binder/1/build/binder.o
  CC [M]  /var/lib/dkms/anbox-binder/1/build/deps.o
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_get_unused_fd_flags’:
/var/lib/dkms/anbox-binder/1/build/binder.c:444:16: error: implicit declaration of function ‘__alloc_fd’ [-Werror=implicit-function-declaration]
  444 |         return __alloc_fd(files, 0, rlim_cur, flags);
      |                ^~~~~~~~~~
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_fd_install’:
/var/lib/dkms/anbox-binder/1/build/binder.c:454:17: error: implicit declaration of function ‘__fd_install’; did you mean ‘fd_install’? [-Werror=implicit-function-declaration]
  454 |                 __fd_install(proc->files, fd, file);
      |                 ^~~~~~~~~~~~
      |                 fd_install
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘task_close_fd’:
/var/lib/dkms/anbox-binder/1/build/binder.c:467:18: error: implicit declaration of function ‘__close_fd’; did you mean ‘close_fd’? [-Werror=implicit-function-declaration]
  467 |         retval = __close_fd(proc->files, fd);
      |                  ^~~~~~~~~~
      |                  close_fd
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_update_page_range’:
/var/lib/dkms/anbox-binder/1/build/binder.c:633:33: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  633 |                 down_write(&mm->mmap_sem);
      |                                 ^~~~~~~~
      |                                 mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:683:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  683 |                 up_write(&mm->mmap_sem);
      |                               ^~~~~~~~
      |                               mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:710:31: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  710 |                 up_write(&mm->mmap_sem);
      |                               ^~~~~~~~
      |                               mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_mmap’:
/var/lib/dkms/anbox-binder/1/build/binder.c:3486:23: error: implicit declaration of function ‘get_files_struct’; did you mean ‘put_files_struct’? [-Werror=implicit-function-declaration]
 3486 |         proc->files = get_files_struct(current);
      |                       ^~~~~~~~~~~~~~~~
      |                       put_files_struct
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /var/lib/dkms/anbox-binder/1/build/binder.o] Error 1
make[1]: *** [Makefile:1851: /var/lib/dkms/anbox-binder/1/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.12.10-arch1-1/build'
make: *** [Makefile:8: all] Error 2`

**Comment by Abhinav1217** [comment]
I am suffering from same issue ..

```
$ sudo make
Password:
make -C /lib/modules/5.12.13-185.current/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.12.13-185.current'
  CC [M]  /usr/src/binder/binder.o
/usr/src/binder/binder.c: In function ‘task_get_unused_fd_flags’:
/usr/src/binder/binder.c:444:9: error: implicit declaration of function ‘__alloc_fd’ [-Werror=implicit-function-declaration]
  444 |  return __alloc_fd(files, 0, rlim_cur, flags);
      |         ^~~~~~~~~~
/usr/src/binder/binder.c: In function ‘task_fd_install’:
/usr/src/binder/binder.c:454:3: error: implicit declaration of function ‘__fd_install’; did you mean ‘fd_install’? [-Werror=implicit-function-declaration]
  454 |   __fd_install(proc->files, fd, file);
      |   ^~~~~~~~~~~~
      |   fd_install
/usr/src/binder/binder.c: In function ‘task_close_fd’:
/usr/src/binder/binder.c:467:11: error: implicit declaration of function ‘__close_fd’; did you mean ‘close_fd’? [-Werror=implicit-function-declaration]
  467 |  retval = __close_fd(proc->files, fd);
      |           ^~~~~~~~~~
      |           close_fd
/usr/src/binder/binder.c: In function ‘binder_update_page_range’:
/usr/src/binder/binder.c:633:19: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  633 |   down_write(&mm->mmap_sem);
      |                   ^~~~~~~~
      |                   mmap_base
/usr/src/binder/binder.c:683:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  683 |   up_write(&mm->mmap_sem);
      |                 ^~~~~~~~
      |                 mmap_base
/usr/src/binder/binder.c:710:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  710 |   up_write(&mm->mmap_sem);
      |                 ^~~~~~~~
      |                 mmap_base
/usr/src/binder/binder.c: In function ‘binder_mmap’:
/usr/src/binder/binder.c:3486:16: error: implicit declaration of function ‘get_files_struct’; did you mean ‘put_files_struct’? [-Werror=implicit-function-declaration]
 3486 |  proc->files = get_files_struct(current);
      |                ^~~~~~~~~~~~~~~~
      |                put_files_struct
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:271: /usr/src/binder/binder.o] Error 1
make[1]: *** [Makefile:1859: /usr/src/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.12.13-185.current'
make: *** [Makefile:8: all] Error 2
```

```
$ uname -a
Linux abhinav-sol 5.12.13-185.current #1 SMP PREEMPT Fri Jun 25 13:06:44 UTC 2021 x86_64 GNU/Linux
```

I am trying to build it from source. Since I am using Solus OS which does not support dkms. 
Last time I built it was with `kernel-5.10.xx` and it was successful. I recently reinstalled my system and have kernel `5.12.xx` and building from source is unsuccessful. I am not sure if it was working on `5.11` kernel or not.

**Comment by mobin-2008** [comment]
OK, Please Updating the Anbox

**Comment by sickcodes** [comment]
Hey @mobin-2008, there's an updated fork on the AUR now: https://aur.archlinux.org/packages/anbox-modules-dkms/
