### ISSUE TITLE
OpenSuse Tumbleweed cannot build modules on kernel 5.8.7-1-default

### ISSUE THREAD

**Issue by Frambooisier** [anbox/anbox-modules#58]
```
flap@SFX:~/Downloads/anbox-modules-master> sudo sh INSTALL.sh 
[sudo] password for root: 

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.7-1-default all KERNEL_SRC=/lib/modules/5.8.7-1-default/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.7-1-default (x86_64)
Consult /var/lib/dkms/anbox-ashmem/1/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.7-1-default all KERNEL_SRC=/lib/modules/5.8.7-1-default/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.8.7-1-default (x86_64)
Consult /var/lib/dkms/anbox-binder/1/build/make.log for more information.
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.8.7-1-default
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.8.7-1-default
ls: cannot access '/dev/binder': No such file or directory
ls: cannot access '/dev/ashmem': No such file or directory
flap@SFX:~/Downloads/anbox-modules-master> 
```

CONTENT OF make.log

```
DKMS make.log for anbox-binder-1 for kernel 5.8.7-1-default (x86_64)
nie, 20 wrz 2020, 01:56:58 CEST
make -C /lib/modules/5.8.7-1-default/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-5.8.7-1-obj/x86_64/default'
  AR      /var/lib/dkms/anbox-binder/1/build/built-in.a
  CC [M]  /var/lib/dkms/anbox-binder/1/build/deps.o
  CC [M]  /var/lib/dkms/anbox-binder/1/build/binder.o
/var/lib/dkms/anbox-binder/1/build/binder.c: In function ‘binder_update_page_range’:
/var/lib/dkms/anbox-binder/1/build/binder.c:633:19: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  633 |   down_write(&mm->mmap_sem);
      |                   ^~~~~~~~
      |                   mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:683:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  683 |   up_write(&mm->mmap_sem);
      |                 ^~~~~~~~
      |                 mmap_base
/var/lib/dkms/anbox-binder/1/build/binder.c:710:17: error: ‘struct mm_struct’ has no member named ‘mmap_sem’; did you mean ‘mmap_base’?
  710 |   up_write(&mm->mmap_sem);
      |                 ^~~~~~~~
      |                 mmap_base
make[3]: *** [/usr/src/linux-5.8.7-1/scripts/Makefile.build:281: /var/lib/dkms/anbox-binder/1/build/binder.o] Error 1
make[2]: *** [/usr/src/linux-5.8.7-1/Makefile:1770: /var/lib/dkms/anbox-binder/1/build] Error 2
make[1]: *** [../../../linux-5.8.7-1/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-5.8.7-1-obj/x86_64/default'
make: *** [Makefile:8: all] Error 2

```

**Comment by unicornlox** [comment]
There is the same problem with manjaro (linux kernel 5.8)

**Comment by kdehairy** [comment]
I have the same issue on archlinux kernel version 5.8.13).

It seems that `mmap_sem` is renamed to `mmap_lock` on kernel 5.8

**Comment by Weirdo1312** [comment]
same issue here on arch linux with 5.8 kernel
logs:
[make.log](https://github.com/anbox/anbox-modules/files/5365902/make.log)
[make(1).log](https://github.com/anbox/anbox-modules/files/5365905/make.1.log)

**Comment by kdehairy** [comment]
I ended up compiling the kernel with the modules built in to overcome this. Now it works!

**Comment by jloqfjgk** [comment]
This issue is likely a duplicate of #49.

**Comment by jack9603301** [comment]
Had the same problem in kubuntu

**Comment by IlgazC** [comment]
I managed to compile the Tumbleweed package using @choff fork however it is for Tumbleweed only. I will submit my changes once I figure at least 15.3 compatibility and sign the modules for secure boot 
https://build.opensuse.org/project/show/home:ilgazcl:branches:home:Sam0523:anbox
